### ISSUE TITLE
Weird behaviour with <lang> tags

### ISSUE THREAD

**Issue by CodedSakura** [KyoriPowered/adventure-text-minimessage#101]
`<red><hover:show_text:"Test"><lang:item.minecraft.stick>` does not produce a red message nor a hover text

but altering it by adding a space between the `<hover>` and `<lang>` or by adding any extra text after the `<lang>` tag does produce the right result
`<red><hover:show_text:"Test"> <lang:item.minecraft.stick>`

**Comment by MiniDigger** [comment]
`<red><hover:show_text:"Test"> <lang:item.minecraft.stick>` isn't actually handled right, since the space vanishes, interesting

**Comment by MiniDigger** [comment]
thanks for the report, fixed your issue, opened a new one for the missing space
