### ISSUE TITLE
Lazy Templates

### ISSUE THREAD

**Issue by Draycia** [KyoriPowered/adventure-text-minimessage#114]
Currently with the Template implementations you must provide the value on template construction.
Which requires either supplying all possible template values for a format, or checking the format manually for the placeholders it contains.

Some values may be more expensive to calculate, and not all formats will use all potential placeholders (example: chat formatters).

Proposal is to have a Template that uses providers or otherwise contain lazy values that are only provided when the template key exists in the format.

**Comment by MiniDigger** [comment]
This pretty much already exists. 
There is a placeholder resolver you can set on your MiniMessage instance (via the builder for example) that gets called when the parser encouters an unknown tag. There you can do your lookup and calc and return the value, or null.
https://docs.adventure.kyori.net/minimessage.html#placeholder

**Comment by kashike** [comment]
We will look into this.

**Comment by MiniDigger** [comment]
api will change before release
