### ISSUE TITLE
rainbow being reset by formatting

### ISSUE THREAD

**Issue by TauCubed** [KyoriPowered/adventure-text-minimessage#128]
the message: `<rainbow><strikethrough>. . . . . . . . .</strikethrough>aaaa</rainbow>`
results in the strikethrough section becoming a rainbow (as it should) however "aaaa" is white even though it's within the rainbow tag.

**Comment by Proximyst** [comment]
What version are you using? Eventually which git commit would it correspond to if you’ve built it yourself?

**Comment by kezz** [comment]
Worth noting I can't reproduce this on [the viewer](https://minidigger.github.io/MiniMessageViewer/?mode=chat_closed&input=%3Crainbow%3E%3Cstrikethrough%3E.%20.%20.%20.%20.%20.%20.%20.%20.%3C%2Fstrikethrough%3Eaaaa%3C%2Frainbow%3E%20%0A) so it's possible this was fixed in the new parser rewrite.

**Comment by TauCubed** [comment]
I'm using `4.1.0-SNAPSHOT` via maven from papermc repo
![image](https://user-images.githubusercontent.com/35522873/126895766-88eada9e-5962-4190-9ecc-2238f8b8c2e7.png)

**Comment by Proximyst** [comment]
Could you retry by compiling the current main branch? I believe this is fixed but unreleased.

**Comment by TauCubed** [comment]
still occurs on `708ef78`

**Comment by kezz** [comment]
Proxi meant the `parser/javacc` branch - can you try on that? You'll need to compile and install it

**Comment by TauCubed** [comment]
Ah, yep.
it's functioning correctly on that branch.
