### ISSUE TITLE
Minimesage strips TranslatableComponent

### ISSUE THREAD

**Issue by SoSeDiK** [KyoriPowered/adventure-text-minimessage#139]
Can be reproduced via this code:
```java
String[] minis = new String[] {"<lang:language.name>", "<lang:language.name>F", ".<lang:language.name>F"};
for (String mimi : minis) {
	Component parsed = MiniMessage.get().parse(mimi);
	player.sendMessage(parsed);
}
```
The result is as follows:
![image](https://user-images.githubusercontent.com/19875118/128744341-8d4e9429-38cf-43e4-a157-9cba13690b31.png)
TranslatableComponent is stripped if it is in the very beginning **and** has anything after it.

Edit: produced jsons for each string:
```json
{"translate":"language.name"}
{"extra":[{"text":"F"}],"text":""}
{"extra":[{"translate":"language.name"},{"text":"F"}],"text":"."}
```

**Comment by kezz** [comment]
For reference, this is a bug in MiniMessage's flattening system. From this point onwards, it doesn't care if the root component is actually meaningful and will happily get rid of it making the incorrect assumption that it will not impact the style of the component. https://github.com/KyoriPowered/adventure-text-minimessage/blob/c4a7e8c8bdc5444875fa0fa01529d60838b20419/src/main/java/net/kyori/adventure/text/minimessage/MiniMessageParser.java#L319

This could be hot fixed, but I believe the better solution is waiting for Adventure 4.9.0 and using the API provided `Component#flatten()` method.
