### ISSUE TITLE
Issues with style tags

### ISSUE THREAD

**Issue by mattboy9921** [KyoriPowered/adventure-text-minimessage#151]
In 4.2.0, I'm seeing weird behavior with style tags. 

For example: take the string: `<dark_red><bold>test</dark_red><green>test</bold> test`
In 4.1.0, it produces this:
![image](https://user-images.githubusercontent.com/15326668/132055381-f20cba73-2758-4dc9-90ec-18a2d1559f7d.png)
In 4.2.0, it produces this:
![image](https://user-images.githubusercontent.com/15326668/132055495-d0ad9597-2cfd-4ece-a7ed-73f742d74a18.png)
It seems like the closing `</dark_red>` tag is somehow closing the `<bold>` tag as well.
This seems to be an issue with all style tags, not just `<bold>`.

**Comment by MiniDigger** [comment]
Sorry for taking so long to get back to you, but this is expected.

Components are a tree, and as such, MiniMessage is a tree too, which means if you close a parent node, all child nodes get closed too.
in your case, the following tree is constructed, which is right
```
Node {
  TagNode('dark_red') {
    TagNode('bold') {
      TextNode('test')
    }
  }
  TagNode('green') {
    TextNode('test</bold> test')
  }
}
```
hopefully this is the last behavior change, minimessage is stabilizing now and will hopefully get a release soon...
