### ISSUE TITLE
Item names are always cursive.

### ISSUE THREAD

**Issue by Trqhxrd** [KyoriPowered/adventure-text-minimessage#153]
I need a little help here.
When I create a TextComponent using MiniMessage, it always becomes cursive, when I use it as an item name. 
If I Use the vanilla color codes, a color code overrides a formatting code. This does not apply in MiniMessage.
Is there some way to reset the formatting codes? I tried using the reset-tag but that did not change anything.

Does anyone have an idea?

Thanks in advance,
Trqhxrd

**Comment by zml2008** [comment]
this is vanilla behaviour - set italics to explicitly false on the returned component to disable it

**Comment by Trqhxrd** [comment]
Thanks!

**Comment by Trqhxrd** [comment]
But do you know a way, how I can universally disable italics? Because now I have to type ".decoration(TextDecoration.ITALICS, false)" for every message and an extra class would be a little overkill...

**Comment by zml2008** [comment]
you can use a client mod I suppose - the italics is added clientside, all you can do is negate it.

However, this is an issue tracker not a support forum. For further assistance please come to our Discord, linked in the README.
