### ISSUE TITLE
Single-character contents of gradient nodes turn black

### ISSUE THREAD

**Issue by zml2008** [KyoriPowered/adventure-text-minimessage#160]
Somehow, colour lerping is producing an output of exactly black, rather than the appropriate point in the gradient.

Sorta related to #147, and demonstrated in the test for the fix of #137, but not fixed by either.

**Comment by rymiel** [comment]
I thought this was sorta intentional? From experience, the output turns black if you use fewer characters than there are colors in a gradient

**Comment by MiniDigger** [comment]
nah, it should use the first color then
