### ISSUE TITLE
Handling of mismatched tags

### ISSUE THREAD

**Issue by zml2008** [KyoriPowered/adventure-text-minimessage#26]
If a user provides `<green>hello</red>`, what would the expected response be? right now the MiniMessage parser appears to ignore the trailing `</red>`. Would it make sense to throw a parse error?

**Comment by MiniDigger** [comment]
decided to handle it like this
![https://i.imgur.com/HhUCIu4.png](https://i.imgur.com/HhUCIu4.png)
by checking if a transformation was actually closed.
