### ISSUE TITLE
Newlines not breaking lines on hover over messages

### ISSUE THREAD

**Issue by PhilCCMG** [KyoriPowered/adventure-text-minimessage#37]
## Description of Bug
When adding a hover effect to a MiniMessage, if you input **\n**, no new line shows.

## Steps to reproduce
- Add MiniMessage to your plugin
- Output a message with **\n** within the quotes. In my case, I have a command called **/utils parse**, and ran `/utils parse <red><hover:show_text:'Message 1\nMessage 2'>My Message`.
- Hover over the message

## Expected Behaviour
There should be a new line created in the lore every time \n is inputted.

## Actual Behaviour
The message shows with the `\n` character and no line break ![example of the bug](https://f.ccm.gg/p/0720/xsGlI.png)

## About Server
Server version 1.16.1 (Paper), using the latest MiniMessage (rebuilt Maven sources as @MiniDigger mentioned in a DM that the current version has been updated).

**Comment by MiniDigger** [comment]
Can't repro, this has to be an issue in how you pass \n into minimessage...

![https://i.imgur.com/EILhEar.png](https://i.imgur.com/EILhEar.png)
```java
  @Test // GH-37
  public void testPhil() {
    final String input = "<red><hover:show_text:'Message 1\nMessage 2'>My Message";
    final String expected = "{\"text\":\"My Message\",\"color\":\"red\",\"hoverEvent\":{\"action\":\"show_text\",\"contents\":{\"text\":\"Message 1\\nMessage 2\"}}}";
    final Component comp = MiniMessageParser.parseFormat(input);

    test(comp, expected);
  }
```

**Comment by PhilCCMG** [comment]
For future reference (if anyone encounters this issue themselves), the reason my example above didn't work was because the backslash character is escaped by the server.

As such, for my example to work, I would have in the `parse` subcommand needed to add:

```java
String message = theMessageInput;
message = message.replace("\\n", "\n");
```
