### ISSUE TITLE
Placeholders should be given as a function

### ISSUE THREAD

**Issue by ItsDoot** [KyoriPowered/adventure-text-minimessage#47]
Placeholders would be much more expressive if they were definable as a `Function<String, Component>`, rather than a strict map or list. This would make it easy to plug in whatever placeholder services you prefer.

**Comment by kashike** [comment]
Should be `Function<String, ComponentLike>`.

**Comment by MiniDigger** [comment]
![https://i.imgur.com/8pFxAqU.png](https://i.imgur.com/8pFxAqU.png)

**Comment by MiniDigger** [comment]
@ItsDoot take a look at that commit please, I assume thats what you wanted?

look at the unit test for usage:
https://github.com/KyoriPowered/adventure-text-minimessage/blob/bye-bye-regex/src/test/java/net/kyori/adventure/text/minimessage/MiniMessageTest.java#L188-L202
