### ISSUE TITLE
Introduce Markdown Flavors

### ISSUE THREAD

**Issue by Andre601** [KyoriPowered/adventure-text-minimessage#56]
While I do like the markdown option of MiniMessage do I strongly believe, that some of the Markdown formatting options are a bit misplaced.

## `~~text~~`
I don't see it, why this is used for underline text. It doesn't make sense visually and many different sites, which use Markdown, such as GitHub or Discord established this syntax as the *strikethrough* option, which Minecraft offers too.

It would make more sense to have this being used as a strikethrough formatting and not as an underline (Which many sites use `__text__` for).

## `||text||`
This could be added to use the obscure/"magic" formatting option of Minecraft.

## How not to break existing uses?
The biggest issue with changing what is used for what formatting is of course, that existing formats would break and display differently.

I believe a good solution could be to offer "flavours" through `MiniMessage.markdown()` where you can provide pre-configured flavours but also provide customized ones as a developer.

For example could `MiniMessage.markdown(Flavour.GITHUB)` turn `~~text~~` from underline to strikethrough, but keep `__text__` still as bold option, while `MiniMessage.markdown(Flavour.DISCORD)` would also change `~~text~~` from underline to strikethrough BUT also changes `__text__` from bold to underline.

I hope those are some ideas to think about

**Comment by MiniDigger** [comment]
I like the flavor idea, fits good with the new parser that also is configureable, ill draft smth up in the next days

**Comment by MiniDigger** [comment]
@Andre601 can you take a look at that commit and tell me what you think? and if I properly implemented your suggestions into the flavors?

**Comment by Andre601** [comment]
Except for one thing (That I mentioned in the commit itself) does the commit look like what I imagined.
I assume LegacyFlavour is the one, current MiniMessage uses for markdown? In that case, does it even make sense to add formatting options there that aren't really available now? Like the Obfuscation.

**Comment by MiniDigger** [comment]
yeah, legacy is what is currently used. Adding obfuscation didn't break anything else so it was an easy win, idk yet how exactly I wanna handle legacy (should it still be default? discord seems to be the fully featured one so maybe that should be default?)

thanks for taking a look, ill remove obfuscation from github then.

**Comment by Andre601** [comment]
I think keeping it to legacy - at least for now - would prevent major breaking changes and unwanted behaviour.
But if you want to use Discord or GitHub as default in the future, would I perhaps deprecate legacy?

**Comment by MiniDigger** [comment]
sounds good, ill just note it in the changelog and change the default eventually
