### ISSUE TITLE
Why is MiniMessageSerializer package private?

### ISSUE THREAD

**Issue by Silthus** [KyoriPowered/adventure-text-minimessage#66]
Is there a reason why the [MiniMessageSerializer is package private](https://github.com/KyoriPowered/adventure-text-minimessage/blob/fb39039d11fdbc97d5eeaa3d3e6c4c39533ea2cc/src/main/java/net/kyori/adventure/text/minimessage/MiniMessageSerializer.java#L59)?

I want to create a message as code and then serialize it using it as the default option when grabbing a translateable message from the config file.
Am I missing something on how to do this properly?

Also is there any documentation on how to use the translateable components? Or fetching and replacing messages from config files? (the typical configurable message use case with using variables).

**Comment by kashike** [comment]
See the [`MiniMessage`](https://github.com/KyoriPowered/adventure-text-minimessage/blob/master/src/main/java/net/kyori/adventure/text/minimessage/MiniMessage.java) class.

**Comment by Silthus** [comment]
Well I see the class but it has no method that takes a component to serialize.

**Comment by kashike** [comment]
`MiniMessage.get().serialize(component)`

**Comment by MiniDigger** [comment]
the docs are translatable components are here: https://docs.adventure.kyori.net/minimessage.html#translatable

**Comment by Silthus** [comment]
Thank you both, I seem to have missed it when looking in the `MiniMessage` class.
