### ISSUE TITLE
Setting strict mode to false has no effect

### ISSUE THREAD

**Issue by Draycia** [KyoriPowered/adventure-text-minimessage#69]
Attempting to parse (invalid?) formats with `strict(false)` results in exceptions still being thrown.

Code:
https://paste.gg/p/anonymous/9f3f06e63d9d4eb19a18d56c0c18520a

**Comment by MiniDigger** [comment]
https://github.com/KyoriPowered/adventure-text-minimessage/commit/e1464112716e857e5eb0cf28d089ca2c45ccfc48
