### ISSUE TITLE
Compound colors do not parse correctly when in markdown mode

### ISSUE THREAD

**Issue by simpleauthority** [KyoriPowered/adventure-text-minimessage#73]
Looks like minimessage breaks when doing a color with an underscore in it in markdown mode. Not quite sure how you'd fix it though.

`<dark_gray>[<gold>Text<dark_gray>]`
=>
It makes `<dark` and then `_gray[<gold>Text<dark_` as italic and then `gray>]` 

:D

**Comment by MiniDigger** [comment]
urg. the markdown thingy is a really "simple" implementation.

maybe it would be acceptable to not parse it, if it's inside a word?

**Comment by kezz** [comment]
Closing following the merge of #145.
