### ISSUE TITLE
Rendering MiniMessage Strings on websites

### ISSUE THREAD

**Issue by OskarZyg** [KyoriPowered/adventure-text-minimessage#84]
Adding some kind of renderer to represent MiniMessage strings on a web page would be a useful addition. Maybe implementing this in some kind of JS renderer or API?

**Comment by MiniDigger** [comment]
https://i.imgur.com/n1qoH9q.png
https://streamable.com/bcw3va
https://i.imgur.com/74stzkM.png

👀

**Comment by MiniDigger** [comment]
https://github.com/KyoriPowered/adventure-webui

https://webui.adventure.kyori.net/
