### ISSUE TITLE
§r always added after serialization

### ISSUE THREAD

**Issue by derech1e** [KyoriPowered/adventure-text-minimessage#86]
Hey, how can I disable the automatic addition of the §r after the whole process? I want the color formatting to remain unchanged.

```
private final LegacyComponentSerializer serializer = LegacyComponentSerializer.builder().build();
private final MiniMessage miniMessage = MiniMessage.get();

final String input = "<gold>Owner <dark_gray>|<gold>a";
final String expected = "§6Owner §8|§6a";
Assertions.assertEquals(serializer.serialize(miniMessage.parse(input)), expected);
```

```
org.opentest4j.AssertionFailedError: 
Expected :§6Owner §8|§6a§r
Actual   :§6Owner §8|§6a
```

**Comment by kashike** [comment]
Why is this an issue for you? I don't see why you would be using the legacy serialiser like this.

**Comment by derech1e** [comment]
> Why is this an issue for you? I don't see why you would be using the legacy serialiser like this.

Then tell me an other way to solve my problem. I read the string from a config file.

**Comment by MiniDigger** [comment]
what exactly are you doing? why do you need to convert to legacy? why dont you send the message as components? 
conversion to legacy is always lossy, after all its a deprecated and legacy format and should be avoided.

**Comment by ken-kentan** [comment]
Adventure hasn't full compatibility with legacy text.
If you want to use legacy text from Json. You should you `net.md_5.bungee.api.chat.TextComponent:: toLegacyText(StringBuilder)`

**Comment by MiniDigger** [comment]
point is: if you use minimessage and adventure, there shouldnt be any reason to use legacy at all
