### ISSUE TITLE
Markdown mode links

### ISSUE THREAD

**Issue by theonlygusti** [KyoriPowered/adventure-text-minimessage#89]
Can you add to the markdown mode `[Click me](http://link/)` transformed to `<click:open_url:http://link/>Click me</click>` ?

**Comment by MiniDigger** [comment]
I don't think this would be a fun (or robust) thing to do with the current markdown parser. this prolly needs a rewrite of said parser (which, let's be fair, I should do anyways)

**Comment by DenWav** [comment]
I could definitely adjust the new parser to support this, but I don't know when I'll get the opportunity to do this. Maybe implementing this could be a way for you to familiarize yourself with the new code @MiniDigger lol

**Comment by DenWav** [comment]
I see now that markdown is handled rather naively now lol. I think a 3rd pass for creating markdown tokens after parsing standard tags would be the best way to implement this using the new parser. Should fix any remaining markdown mode issues you have.

**Comment by kezz** [comment]
Closing following the merge of #145.
