### ISSUE TITLE
The <pre> tag cannot safely be used for user input

### ISSUE THREAD

**Issue by Exlll** [KyoriPowered/adventure-text-minimessage#97]
If the user input contains `</pre>`, the scope of the pre tag is terminated early.

Example code:
```java
String message = String.join(" ", args);
List<Template> templates = List.of(
        Template.of("username", sender.getName()),
        Template.of("message", message)
);
Component component = MiniMessage.get().parse(
        "<username>: <pre><message>",
        templates
);
sender.sendMessage(component);
```

Example message:

```
/example </pre> <click:run_command:/reload confirm>>>>Click me<<<
```

**Comment by Ehhthan** [comment]
Just tested this and can confirm this happens. Seems pretty severe as it can be used for tricking players, including staff members, into executing any command you want.

**Comment by Exlll** [comment]
I'm not familiar with the code but I'm not sure whether there is an easy way to fix this without changing the semantics of the tag. One possible solution would be to change the lexer and let the pre token match until either `EOF` or the **last** closing `</pre>` tag in the input. This, of course, would be a breaking change and would also introduce the need for additional pre tags, like `<pre:1>`, `<pre:2>`, etc.

A workaround would be to introduce some new API for escaping user input in a way that changes or removes `</pre>` tags in the input (I don't know if something like this already exists). 

In the meantime, it might also be a good idea to update the [documentation](https://docs.adventure.kyori.net/minimessage.html#pre) and tell users to remove any `</pre>` tags from user input.

**Comment by MiniDigger** [comment]
decided to remove (as in, escape) pre end tags in string templates
